name: FSN Panel Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pyinstaller
        pip install -r requirements.txt

    - name: Run tests with pytest
      run: pytest

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --noconfirm --onefile --windowed --uac-admin "main.py"

    - name: Copy settings folder
      run: |
        mkdir dist/settings
        xcopy settings dist/settings /E /I /Y

    - name: Create ZIP package
      run: |
        powershell Compress-Archive -Path dist\* -DestinationPath FSN_Panel.zip -Force

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: FSN_Panel_Package
        path: FSN_Panel.zip
